cars/urls.py
from django.urls import path
from . import views


app_name = 'cars'

urlpatterns = [
    path('', views.CarListView.as_view() , name='cars'),
    path('detail/<slug>/', views.CarDetail, name='car-detail'),
    path('brands/<slug>/', views.BrandListView.as_view(), name='brand'),
    path('brands/', views.BrandsView.as_view(), name='brands'),
    path('car/for-sale/', views.CarListSaleView.as_view(), name='car-for-sale'),
    path('for-hire/', views.CarListHireView.as_view(), name='car-for-hire'),
    path('spare-parts/', views.SparePartListView.as_view(), name='spare-parts'),
    path('spare-part/<slug>/', views.SparePartDetail, name='spare-part-detail'),
    path('driving-schools/', views.SchoolListView.as_view(), name='schools'),
    path('driving-school/<slug>/', views.SchoolDetail, name='school-detail'),
]

core/urls.py
from django.urls import path
from .views import *


app_name = 'core'

urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),

    path('category/<str:category>/', CategoryListView.as_view(), name='category'),
    path('locality/<str:locality>/', LocalityListView.as_view(), name='locality'),
    path('region/<str:region>/', RegionListView.as_view(), name='region'),
    path('search/', SearchBarListView.as_view(), name='search'),
    

    path('ajax_subscriptionform/', subscriptionForm),
    path('contact-us/', contactPage, name='contact'),
    path('about-us/', aboutPage, name='about'),
    path('terms-and-conditions/', ConditionPage, name='conditions'),
    path('privacy-policy/', PrivacyPolicyPage, name='privacy-policy'),
    path('return-policy/', ReturnPolicyPage, name='return-policy'),
    path('faqs/', FaqsPage, name='faqs'),
    path('safety-tips/', SafetyPage, name='safety-tips'),
]

property/urls.py
from django.urls import path
from .views import *


app_name = 'property'

urlpatterns = [
    path('', PropertyListView.as_view(), name='property'),
    path('for-sale/', ForSaleListView.as_view(), name='for-sale'),
    path('<slug>/for-sale/', CategoryForSaleListView.as_view(), name='for-sale-cate'),
    path('for-rent/', ForRentListView.as_view(), name='for-rent'),
    path('<slug>/for-rent/', CategoryForRentListView.as_view(), name='for-rent-cate'),

    path('detail/<slug>/', propertyDetail, name='property-detail'),


    path('search/', SearchListView.as_view(), name='search'),


    path('check/', checkPage, name='check'),

    path('land/', LandListView.as_view(), name='land'),

    path('real-estates/', RealEstateListView.as_view(), name='real-estates'),
    path('real-estate/detail/<slug>/', RealestateDetail, name='realestate-detail'),
    path('hotels/', HotelListView.as_view(), name='hotels'),
    path('hotel/detail/<slug>/', HotelDetail, name='hotel-detail'),
    path('hotel-rooms/', HotelRoomListView.as_view(), name='hotel-rooms'),
    path('hotel-room/detail/<slug>/', HotelRoomDetail, name='hotel-room-detail'),
]

sandvet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('property/', include('property.urls', namespace='property')),
    path('cars/', include('cars.urls', namespace='cars')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property/models.py
from datetime import datetime
from django.db import models
from django.shortcuts import reverse
from autoslug import AutoSlugField
from autoslug.settings import slugify as default_slugify
from core.models import  Locality, REGIONS_LIST, Booking
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.

def custom_slugify(value):
    return default_slugify(value).replace(' ', '-')


def get_dated(created_at):
    time = datetime.now()
    if created_at.day == time.day:
        return str(time.hour - created_at.hour) + " hours ago"
    else:
        if created_at.month == time.month:
            return str(time.day - created_at.day) + " days ago"
        else:
            if created_at.year == time.year:
                return str(time.month - created_at.month) + " months ago"
            else:
                return str(time.year - created_at.year) + " year(s) ago"
    return created_at

# Create your models here.
STAR_RATING = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
)

PRICE_NEGORIABLE = (
    ('yes', 'Yes'),
    ('no', 'No'),
)



PROPERTY_PURPOSE_TYPE = [
    ('sale', 'sale'),
    ('rent', 'rent'),
]

class Category(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(populate_from='title',unique_with='created_at__month',slugify=custom_slugify )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id']

    def get_category_url(self):
        return reverse("core:category", kwargs={
            'slug': self.slug
        })

    def get_for_sale_category_url(self):
        return reverse("property:for-sale-cate", kwargs={
            'slug': self.slug
        })

    def get_for_rent_category_url(self):
        return reverse("property:for-rent-cate", kwargs={
            'slug': self.slug
        })





class LandProperty(models.Model):
    property = models.OneToOneField("Property",  on_delete=models.CASCADE, related_name='landproperty', null=True)
    dimension = models.CharField(max_length=200, null=True, blank=True)
    area = models.CharField(max_length=200, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.property.title




class HouseProperty(models.Model):
    property = models.OneToOneField("Property",  on_delete=models.CASCADE, related_name='houseproperty', null=True)
    #
    bed = models.PositiveIntegerField(default=1, null=True, blank=True)
    bath = models.PositiveIntegerField(default=1, null=True, blank=True)
    garage = models.PositiveIntegerField(default=0, null=True, blank=True)
    area = models.CharField(max_length=200, null=True, blank=True)
    amenities = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.property.title







class Property(models.Model):
    title = models.CharField(max_length=200,null=True)
    price = models.FloatField()
    price_negotiable = models.CharField(max_length=3, choices=PRICE_NEGORIABLE, default='no')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    purpose = models.CharField(max_length=4, choices=PROPERTY_PURPOSE_TYPE, default='sale')
    region = models.CharField(choices=REGIONS_LIST, max_length=20, null=True)
    locality = models.ForeignKey(Locality, on_delete=models.CASCADE, null=True)
    location_address = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='property/')
    description = models.TextField(null=True, blank=False)
    views = models.PositiveIntegerField(default=0)
    featured = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(
                populate_from='title', 
                unique_with='created_at__month',
                slugify=custom_slugify
            )
    owned_by = models.ForeignKey("RealEstate", on_delete=models.CASCADE, null=True, blank=True, related_name="realestate")

    def __str__(self):
        return self.title

    @property
    def imageURL(self):
        try:
            url = self.image.url 
        except:
            url = ''
        return url

    def get_absolute_url(self):
        return reverse("property:property-detail", kwargs={
            'slug': self.slug
        })

    def get_date(self):
        time = datetime.now()
        if self.created_at.day == time.day:
            return str(time.hour - self.created_at.hour) + " hours ago"
        else:
            if self.created_at.month == time.month:
                return str(time.day - self.created_at.day) + " days ago"
            else:
                if self.created_at.year == time.year:
                    return str(time.month - self.created_at.month) + " months ago"
                else:
                    return str(time.year - self.created_at.year) + " year(s) ago"
        return self.created_at


    def get_land_details(self):
        return LandProperty.objects.get(property=self)


class PropertyImage(models.Model):
    prop = models.ForeignKey(Property, on_delete=models.CASCADE, null=True, blank=True, related_name='propertyimages')
    images = models.ImageField(null=True, blank=True, upload_to="property/imgs/")

    def __str__(self):
        return self.property.title

    @property
    def imageURL(self):
        try:
            url =self.images.url 
        except:
            url = ''
        return url




class RealEstate(models.Model):
    title = models.CharField(max_length=200,null=True, unique=True)
    region = models.CharField(choices=REGIONS_LIST, max_length=20, null=True, blank=True)
    locality = models.ForeignKey(Locality, on_delete=models.CASCADE, null=True, blank=True)
    location_address = models.CharField(max_length=200, null=True)
    url = models.URLField(max_length=200, null=True, blank=True)
    logo = models.ImageField(upload_to='realeastate/logo', null=True)
    image = models.ImageField(upload_to='realeastate/')
    description = models.TextField(null=True, blank=False)
    views = models.PositiveIntegerField(default=0)
    featured = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(
                populate_from='title', 
                unique_with='created_at__month',
                slugify=custom_slugify
            )

    def __str__(self):
        return self.title

    @property
    def imageURL(self):
        try:
            url = self.image.url 
        except:
            url = ''
        return url
    
    @property
    def logoURL(self):
        try:
            url = self.logo.url 
        except:
            url = ''
        return url

    def get_absolute_url(self):
        return reverse("property:realestate-detail", kwargs={
            'slug': self.slug
        })

    def get_date(self):
        time = datetime.now()
        if self.created_at.day == time.day:
            return str(time.hour - self.created_at.hour) + " hours ago"
        else:
            if self.created_at.month == time.month:
                return str(time.day - self.created_at.day) + " days ago"
            else:
                if self.created_at.year == time.year:
                    return str(time.month - self.created_at.month) + " months ago"
                else:
                    return str(time.year - self.created_at.year) + " year(s) ago"
        return self.created_at


    def get_land_details(self):
        return LandProperty.objects.get(property=self)




class RealEstateImage(models.Model):
    realestate = models.ForeignKey(RealEstate, on_delete=models.CASCADE, null=True, blank=True, related_name='realestateimages')
    images = models.ImageField(null=True, blank=True, upload_to="realestate/imgs/")

    def __str__(self):
        return self.realestate.title

    @property
    def imageURL(self):
        try:
            url = self.images.url 
        except:
            url = ''
        return url



class SocialHandle(models.Model):
    realestate = models.OneToOneField(RealEstate, on_delete=models.CASCADE, null=True, blank=True, related_name='socialhandle')
    facebook = models.URLField(max_length=200, null=True, blank=True)
    linkedIn = models.URLField(max_length=200, null=True, blank=True)
    instagram = models.URLField(max_length=200, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return self.realestate.title



class Testimony(models.Model):  
    name = models.CharField(max_length=200, null=True)
    message = models.TextField()
    image = models.ImageField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.name


    @property
    def imageURL(self):
        try:
            url = self.image.url 
        except:
            url = ''
        return url

   


class Subscription(models.Model):
    PROPERTY_PURPOSE_TYPE = [
        ('sale', 'for sale'),
        ('rent', 'for rent'),
    ]
    email = models.CharField(max_length=200, null=True)
    locality = models.ForeignKey(Locality, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    purpose = models.CharField(max_length=4, choices=PROPERTY_PURPOSE_TYPE, default='sale')
    bed = models.PositiveIntegerField(default=1)
    from_price = models.FloatField(null=True)
    to_price = models.FloatField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
  

    def __str__(self):
        return self.email

   

class HospitalityCategory(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True, unique=True)

property/forms.py
from django import forms

templates/property/land.html
{% extends "base.html" %}
{% block head_title %}{% endblock %}
{% block content %}
{% load crispy_forms_tags %} 
<div class="container mt-3">
    <div class="row">
        <div class="navigaiton card col-12">
            <a class="navLinks" href="{% url 'core:index' %}">Home</a>
            <a class="navLinks" href="{% url 'property:property' %}">Property</a>
            <a class="navLinks">Land</a>
        </div>
    </div>
    <div class="row"> 
        <div class="col-md-3">
            <div class="py-3 filter-sec">
                <div class="d-flex align-items-center justify-content-between panel__cardhead">
                    <div><h3>Fliter</h3></div>
                    <div class="view-change"></div>
                </div>
                 <!--list-head end-->
                <div class="listings panel__cardbody d-flex">
                    <div class="list_products col-12 m-0 p-0">
                    <form  class="">
                        <div class="row">
                            {% for field in filter.form %}
                                <div class="col-12">
                                    {{ field|as_crispy_field }}
                                </div>
                            {% endfor %}
                                <div class="col-12">
                                    <button type="submit" class="btn2">Filter</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>     
        </div> 
        <div class="col-md-9">
            <div class="listing-directs py-3">   
                    <div class="">
                        <div class="row align-items-center justify-content-between panel__cardhead">
                            <div class="sortby">
                                <span>Sort by:</span>
                                <select class="select">
                                    <option value="">Relevant</option>
                                    <option value="">Oldest</option>
                                    <option value="">Most Viewed</option>
                                    <option value="">Higher price</option>
                                    <option value="">Lower price</option>
                                </select>
                            </div><!--sortby end-->
                            <div class="view-change">
                                <ul class="nav nav-tabs sw-order-view">
                                    <li class="nav-item">
                                        <a href="javascript:void(0);" class="nav-link grid view-type " data-ref="grid"><i class="fa fa-th-large"></i></a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="javascript:void(0);" class="nav-link list view-type active" data-ref="list"><i class="fa fa-th-list"></i></a>
                                    </li>
                                </ul>
                            </div><!--view-change end-->
                        </div>

                        <!--list-head end-->
                        <div class="listings panel__cardbody row">
                            <div class="list_products col-12 m-0 p-0 list">
                                <div class="row">
                                    {% for list in lists.property_set.all %}
                                        <div class="col-md-12 mb-3">
                                            {% include 'includes/list.html' %}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="col-12">
                                {% include 'includes/pagination.html' %}
                            </div>
                        </div><!--tab-content end-->
                    </div>
                </div>
            </div>    
        </div>
    </div>

{% endblock %}

templates/property/list.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %} 
<div class="container mt-3">
    <div class="row">
        <div class="col-12">
            <div class="navigaiton card">
                <a class="navLinks" href="{% url 'core:index' %}">Home</a>
                <a class="navLinks" href="{% url 'property:property' %}">Property</a>
                {% if page_title == 'Hotel Rooms' %}
                    <a class="navLinks" href="{% url 'property:hotels' %}">Hotels</a>
                {% endif %}
                <a class="navLinks">{{ page_title }}</a>
            </div>
        </div>
    </div>

    <div class="row mb-5"> 
        <div class="col-md-3">
            <div class="py-3 filter-sec">
                <div class="d-flex align-items-center justify-content-between panel__cardhead">
                    <div><h3>Fliter</h3></div>
                    <div class="view-change"></div>
                </div>
                 <!--list-head end-->
                <div class="listings panel__cardbody d-flex">
                    <div class="list_products col-12 m-0 p-0">
                    <form  class="">
                        <div class="row">
                            {% for field in filter.form %}
                                <div class="col-12">
                                    {{ field|as_crispy_field }}
                                </div>
                            {% endfor %}
                                <div class="col-12">
                                    <button type="submit" class="btn2">Filter</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>     
        </div> 
        <div class="col-md-9">
            <div class="listing-directs py-3 ">   
                    <div class="col-12">
                        <div class="row align-items-center justify-content-between panel__cardhead">
                            <div class="sortby">
                                {{lists|length}}
                            </div><!--sortby end-->
                            <div class="view-change">
                                <ul class="nav nav-tabs sw-order-view">
                                    <li class="nav-item">
                                        <a href="javascript:void(0);" class="nav-link grid view-type " data-ref="grid"><i class="fa fa-th-large"></i></a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="javascript:void(0);" class="nav-link list view-type active" data-ref="list"><i class="fa fa-th-list"></i></a>
                                    </li>
                                </ul>
                            </div><!--view-change end-->
                        </div>

                        <!--list-head end-->
                        <div class="listings panel__cardbody row propetyList">
                            <div class="list_products col-12 m-0 p-0 list">
                                <div class="row">
                                    {% for list in lists%}
                                        <div class="col-md-12 mb-3">
                                            {% include 'includes/list.html' %}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="col-12">
                                {% include 'includes/pagination.html' %}
                            </div>
                        </div><!--tab-content end-->
                    </div>
                </div>
            </div>    
        </div>
    </div>

{% endblock %}

templates/property/search-list.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %} 
<div class="container mt-3">
    <div class="row">
        <div class="col-12">
            <div class="navigaiton card">
                <a class="navLinks" href="{% url 'core:index' %}">Home</a>
                <a class="navLinks" href="{% url 'property:property' %}">Property</a>
                {% if page_title == 'Hotel Rooms' %}
                    <a class="navLinks" href="{% url 'property:hotels' %}">Hotels</a>
                {% endif %}
                <a class="navLinks">{{ page_title }}</a>
            </div>
        </div>
    </div>

    <div class="row mb-5"> 
        <div class="col-md-3">
            <div class="py-3 filter-sec">
                <div class="d-flex align-items-center justify-content-between panel__cardhead">
                    <div><h3>Fliter</h3></div>
                    <div class="view-change"></div>
                </div>
                 <!--list-head end-->
                <div class="listings panel__cardbody d-flex">
                    <div class="list_products col-12 m-0 p-0">
                    <form  class="" action="
                        {% if form_category == 'property' %}
                            {% url 'property:property' %}
                        {% elif form_category == 'hotels' %}
                            {% url 'property:hotels' %}
                        {% elif form_category == 'hotelrooms' %}
                            {% url 'property:hotel-rooms' %}
                        {% elif form_category == 'realestates' %}
                            {% url 'property:real-estates' %}
                        {% elif form_category == 'lands' %}
                            {% url 'property:land' %}
                        {% elif form_category == 'cars' %}
                            {% url 'cars:cars' %}
                        {% elif form_category == 'schools' %}
                            {% url 'cars:schools' %}
                        {% elif form_category == 'spareparts' %}
                            {% url 'cars:spare-parts' %}
                        {% endif %}
                    ">
                        <div class="row">
                            {% for field in filter.form %}
                                <div class="col-12">
                                    {{ field|as_crispy_field }}
                                </div>
                            {% endfor %}
                                <div class="col-12">
                                    <button type="submit" class="btn2">Filter</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>     
        </div> 
        <div class="col-md-9">
            <div class="listing-directs py-3 ">   
                    <div class="col-12">
                        <div class="row align-items-center justify-content-between panel__cardhead">
                            <div class="sortby">
                                {{lists|length}}
                            </div><!--sortby end-->
                            <div class="view-change">
                                <ul class="nav nav-tabs sw-order-view">
                                    <li class="nav-item">
                                        <a href="javascript:void(0);" class="nav-link grid view-type " data-ref="grid"><i class="fa fa-th-large"></i></a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="javascript:void(0);" class="nav-link list view-type active" data-ref="list"><i class="fa fa-th-list"></i></a>
                                    </li>
                                </ul>
                            </div><!--view-change end-->
                        </div>

                        <!--list-head end-->
                        <div class="listings panel__cardbody row propetyList">
                            <div class="list_products col-12 m-0 p-0 list">
                                <div class="row">
                                    {% for list in lists%}
                                        <div class="col-md-12 mb-3">
                                            {% if form_category == 'cars' %}
                                                {% include 'cars/car-list.html' %}
                                            {% elif form_category == 'spareparts' %}
                                                {% include 'cars/spare-list.html' %}
                                            {% elif form_category == 'schools' %}
                                                {% include 'cars/school-list.html' %}
                                            {% else %}
                                                {% include 'includes/list.html' %}
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="col-12">
                                {% include 'includes/pagination.html' %}
                            </div>
                        </div><!--tab-content end-->
                    </div>
                </div>
            </div>    
        </div>
    </div>

{% endblock %}