cars/urls.py
from django.urls import path
from . import views


app_name = 'cars'

urlpatterns = [
    path('', views.CarListView.as_view() , name='cars'),
    path('detail/<slug>/', views.CarDetail, name='car-detail'),
    path('brands/<slug>/', views.BrandListView.as_view(), name='brand'),
    path('brands/', views.BrandsView.as_view(), name='brands'),
    path('car/for-sale/', views.CarListSaleView.as_view(), name='car-for-sale'),
    path('for-hire/', views.CarListHireView.as_view(), name='car-for-hire'),
    path('spare-parts/', views.SparePartListView.as_view(), name='spare-parts'),
    path('spare-part/<slug>/', views.SparePartDetail, name='spare-part-detail'),
    path('driving-schools/', views.SchoolListView.as_view(), name='schools'),
    path('driving-school/<slug>/', views.SchoolDetail, name='school-detail'),
]

core/urls.py
from django.urls import path
from .views import *


app_name = 'core'

urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),

    path('category/<str:category>/', CategoryListView.as_view(), name='category'),
    path('locality/<str:locality>/', LocalityListView.as_view(), name='locality'),
    path('region/<str:region>/', RegionListView.as_view(), name='region'),
    path('search/', SearchBarListView.as_view(), name='search'),
    

    path('ajax_subscriptionform/', subscriptionForm),
    path('contact-us/', contactPage, name='contact'),
    path('about-us/', aboutPage, name='about'),
    path('terms-and-conditions/', ConditionPage, name='conditions'),
    path('privacy-policy/', PrivacyPolicyPage, name='privacy-policy'),
    path('return-policy/', ReturnPolicyPage, name='return-policy'),
    path('faqs/', FaqsPage, name='faqs'),
    path('safety-tips/', SafetyPage, name='safety-tips'),
]

dashboard/urls.py
from django.urls import path
from .views import core, prop, cars

app_name = 'dashboard'

urlpatterns = [
    path("accounts/auth/", core.auth, name="auth"),

    path('', core.dashboardPage, name='dashboard'),
    path('locality/', core.LocalityPage, name='locality'),
    path('locality/add/', core.LocalityAddPage, name='locality-add'),
    path('locality/<int:id>/edit/', core.LocalityEditPage, name='edit-locality'),
    path('locality/<int:id>/delete/', core.DeleteLocality, name='delete-locality'),

    # Bookings
    path('bookings/', core.BookingsPage, name='bookings'),
    path('booking/<int:id>/view/', core.ViewBooking, name='view-booking'),
    path('booking/<int:id>/delete/', core.DeleteBooking, name='delete-booking'),

    path('bookings/cars/', core.CarBookingsPage, name='car-bookings'),
    path('bookings/spareparts/', core.SparePartBookingsPage, name='sparepart-bookings'),
    path('bookings/driving-school/', core.SchoolBookingsPage, name='school-bookings'),
    path('bookings/properties/', core.PropertyBookingsPage, name='properties-bookings'),
    path('bookings/hotels/', core.HotelBookingsPage, name='hotels-bookings'),
    path('bookings/hotel-rooms/', core.HotelRoomBookingsPage, name='hotelrooms-bookings'),
    path('bookings/real-estates/', core.RealEstateBookingsPage, name='realestates-bookings'),

    # Propery
    path('properties/', prop.propertyPage, name='property'),
    path('property/add/', prop.PropertyAddPage, name='add-property'),
    path('property/<int:id>/edit/', prop.PropertyEditPage, name='edit-property'),
    path('property/<int:id>/view/', prop.ViewProperty, name='view-property'),
    path('property/<int:id>/delete/', prop.DeleteProperty, name='delete-property'),
    path('property/image/<int:id>/delete/', prop.DeletePropertyImage, name='delete-property-image'),

    # Property Category
    path('property/categories/', prop.CategoryPage, name='categories'),
    path('property/category/add/', prop.CategoryAddPage, name='add-category'),
    path('property/category/<int:id>/edit/', prop.CategoryEditPage, name='edit-category'),
    path('property/category/<int:id>/delete/', prop.DeleteCategory, name='delete-category'),

    # Real Estate
    path('real-estates/', prop.RealEstatePage, name='realestates'),
    path('real-estate/add/', prop.RealEstateAddPage, name='add-realestate'),
    path('real-estate/<int:id>/view/', prop.ViewRealEstate, name='view-realestate'),
    path('real-estate/<int:id>/edit/', prop.RealEstateEditPage, name='edit-realestate'),
    path('real-estate/<int:id>/delete/', prop.DeleteRealEstate, name='delete-realestate'),
    path('real-estate/<int:id>/featured/', prop.FeaturedRealEstate, name='featured-realestate'),
    path('real-estate/image/<int:id>/delete/', prop.DeleteRealEstateImage, name='delete-realestate-image'),

    # Hotels
    path('hotels/', prop.HotelsPage, name='hotels'),
    path('hotel/add/', prop.HotelAddPage, name='add-hotel'),
    path('hotel/<int:id>/view/', prop.ViewHotel, name='view-hotel'),
    path('hotel/<int:id>/featured/', prop.FeaturedHotel, name='featured-hotel'),
    path('hotel/<int:id>/edit/', prop.HotelEditPage, name='edit-hotel'),
    path('hotel/<int:id>/delete/', prop.DeleteHotel, name='delete-hotel'),
    path('hotel/image/<int:id>/delete/', prop.DeleteHotelImage, name='delete-hotel-image'),

    # Hotels Room
    path('hotel-rooms/', prop.HotelRoomsPage, name='hotel-rooms'),
    path('hotel-room/add/', prop.HotelRoomAddPage, name='add-hotel-room'),
    path('hotel-room/<int:id>/view/', prop.ViewHotelRoom, name='view-hotel-room'),
    path('hotel-room/<int:id>/edit/', prop.HotelRoomEditPage, name='edit-hotel-room'),
    path('hotel-room/<int:id>/featured/', prop.FeaturedHotelRoom, name='featured-hotel-room'),
    path('hotel-room/<int:id>/delete/', prop.DeleteHotelRoom, name='delete-hotel-room'),
    path('hotel-room/image/<int:id>/delete/', prop.DeleteHotelRoomImage, name='delete-hotel-room-image'),

    # Cars
    path('cars/', cars.CarPage, name='car'),
    path('car/add/', cars.CarAddPage, name='add-car'),
    path('car/<int:id>/delete/', cars.DeleteCar, name='delete-car'),
    path('car/<int:id>/edit/', cars.CarEditPage, name='edit-car'),
    path('car/<int:id>/view/', cars.ViewCar, name='view-car'),
    path('car/image/<int:id>/delete/', cars.DeleteCarImage, name='delete-car-image'),
    path('car/<int:id>/featured/', cars.FeaturedCar, name='featured-car'),

    path('brands/', cars.BrandPage, name='brands'),
    path('brand/add/', cars.BrandAddPage, name='add-brand'),
    path('brand/<int:id>/featured/', cars.FeaturedBrand, name='featured-brand'),
    path('brand/<int:id>/view/', cars.ViewBrand, name='view-brand'),
    path('brand/<int:id>/delete/', cars.DeleteBrand, name='delete-brand'),
    path('brand/<int:id>/edit/', cars.BrandEditPage, name='edit-brand'),
    
    path('car/types/', cars.TypePage, name='types'),
    path('car/type/add/', cars.TypeAddPage, name='add-type'),
    path('car/type/<int:id>/edit/', cars.TypeEditPage, name='edit-type'),
    path('car/type/<int:id>/delete/', cars.DeleteType, name='delete-type'),

    # SPARE PARTS
    path('car/spare-parts/', cars.SparePartPage, name='spare-parts'),
    path('car/spare-part/add/', cars.SparePartAddPage, name='add-spare-part'),
    path('car/spare-part/<int:id>/Edit/', cars.SparePartEditPage, name='edit-spare-part'),
    path('car/spare-part/<int:id>/view/', cars.ViewSparePart, name='view-spare-part'),
    path('car/spare-part/<int:id>/featured/', cars.FeaturedSparePart, name='featured-spare-part'),
    path('car/spare-part/<int:id>/delete/', cars.DeleteSparePart, name='delete-spare-part'),
    path('car/spare-part/image/<int:id>/delete/', cars.DeleteSparePartImage, name='delete-sparepart-image'),
    
    # DRIVING SCHOOL
    path('car/driving-schools/', cars.SchoolPage, name='schools'),
    path('car/driving-school/add/', cars.SchoolAddPage, name='add-school'),
    path('car/driving-school/<int:id>/Edit/', cars.SchoolEditPage, name='edit-school'),
    path('car/driving-school/<int:id>/view/', cars.ViewSchool, name='view-school'),
    path('car/driving-school/<int:id>/featured/', cars.FeaturedSchool, name='featured-school'),
    path('car/driving-school/<int:id>/delete/', cars.DeleteSchool, name='delete-school'),
    path('car/driving-school/image/<int:id>/delete/', cars.DeleteSchoolImage, name='delete-school-image'),

    # Ajax URLS
    path("dashboard/property/add/land/", prop.ajaxPropertyLandAdd, name="add-land-property"),
    path("dashboard/property/add/house/", prop.ajaxPropertyHouseAdd, name="add-house-property"),
    path("dashboard/logout/", core.authLogout, name="logout"),

]

property/urls.py
from django.urls import path
from .views import *


app_name = 'property'

urlpatterns = [
    path('', PropertyListView.as_view(), name='property'),
    path('for-sale/', ForSaleListView.as_view(), name='for-sale'),
    path('<slug>/for-sale/', CategoryForSaleListView.as_view(), name='for-sale-cate'),
    path('for-rent/', ForRentListView.as_view(), name='for-rent'),
    path('<slug>/for-rent/', CategoryForRentListView.as_view(), name='for-rent-cate'),

    path('detail/<slug>/', propertyDetail, name='property-detail'),


    path('search/', SearchListView.as_view(), name='search'),


    path('check/', checkPage, name='check'),

    path('land/', LandListView.as_view(), name='land'),

    path('real-estates/', RealEstateListView.as_view(), name='real-estates'),
    path('real-estate/detail/<slug>/', RealestateDetail, name='realestate-detail'),
    path('hotels/', HotelListView.as_view(), name='hotels'),
    path('hotel/detail/<slug>/', HotelDetail, name='hotel-detail'),
    path('hotel-rooms/', HotelRoomListView.as_view(), name='hotel-rooms'),
    path('hotel-room/detail/<slug>/', HotelRoomDetail, name='hotel-room-detail'),
]

sandvet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('property/', include('property.urls', namespace='property')),
    path('cars/', include('cars.urls', namespace='cars')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
{% load crispy_forms_tags %} 
<section class="bottom__section">
    <div class="container placeholder-container">
        <div class="row hideView">
            <div class="widget col-xl-3 col-sm-6 col-md-4">
                <div class="widget-footer-contacts">
                    <h3>For rent</h3>
                    <ul class="footer-list">
                        <li><span class="value"><a href="{% url 'cars:car-for-hire' %}">Car For Hire</a></li>
                        <li><span class="value"><a href="{% url 'property:for-rent' %}">Property for rent</a></span></li>
                        {% for cate in category_list_nav %}
                        <li><span class="value"><a href="{{cate.get_for_rent_category_url}}">{{cate.title}} for rent</a></span></li>
                        {%endfor%}
                    </ul>
                </div>
                <div class="widget-footer-contacts mt-3">
                    <h3>For Sale</h3>
                    <ul class="footer-list">
                        <li><span class="value"><a href="{% url 'cars:car-for-sale' %}">Cars for sale</a></li>
                        <li><span class="value"><a href="{% url 'property:for-sale' %}">Property for sale</a></span></li>
                        {% for cate in category_list %}
                        <li><span class="value"><a href="{{cate.get_for_sale_category_url}}">{{cate.title}} for sale</a></span></li>
                        {%endfor%}
                    </ul>
                </div>
            </div>
            <div class="widget col-xl-3 col-sm-6 col-md-4">
                <div class="widget-footer-contacts">
                    <h3>Top Car Brands</h3>
                    <ul class="footer-list">
                        {% for tbrand in brands_list %}
                        <li><span class="value"><a href="{{tbrand.get_absolute_url}}">{{tbrand.name}} </a></span></li>
                        {%endfor%}
                    </ul>
                </div>
                <div class="widget-footer-contacts mt-3">
                    <h3>Top driving schools</h3>
                    <ul class="footer-list">                
                        {% for list in driving_list %}
                            <li><span class="value"><a href="{{list.get_absolute_url}}">{{list.title}}</a></span></li>
                        {%endfor%}
                    </ul>
                </div>
            </div>
            <div id="widget-follow-us-1" class="widget footer-regular widget-follow-us block-selio col-xl-3 col-sm-12 col-md-5">
                <div class="widget-footer-contacts">
                    <h3>Top Hotels</h3>
                    <ul class="footer-list">                
                        {% for list in hotels_list %}
                            <li><span class="value"><a href="{{list.get_absolute_url}}">{{list.title}}</a></span></li>
                        {%endfor%}
                    </ul>
                </div>
                <div class="widget-footer-contacts mt-3">
                    <h3>Top Real Estates</h3>
                    <ul class="footer-list">                
                        {% for list in realestates_list %}
                            <li><span class="value"><a href="{{list.get_absolute_url}}">{{list.title}}</a></span></li>
                        {%endfor%}
                    </ul>
                </div>
            </div> 
            <div id="widget-footer-contacts-1" class="widget footer-regular widget-footer-contacts block-selio col-xl-3 col-sm-6 col-md-3">
                <div class="widget-footer-contacts">
                    <h3>Contact Us</h3>
                    <ul class="footer-list">                
                        <li><i class="fa fa-map-marker"></i> <span class="value">University of Ghana, East Legon - Accra, Ghana</span></li>
                        <li><i class="fa fa-phone"></i> <span class="value"><a href="tel://+233507321204">+233 50 732 1204</a></span></li>
                        <li><i class="fa fa-phone"></i> <span class="value"><a href="tel://+233554748768">+233 55 474 8768</a></span></li>
                        <li><i class="fa fa-envelope"></i> <span class="value"><a href="mailto:support@sandvet.com">support@sandvet.com</a></span></li>

                        <li><i class="fa fa-chevron-circle-right"></i><span class="value"><a href="{% url 'core:contact' %}">Contact Us</a></span></li>
                    </ul>

                </div>
                <div class="widget-footer-contacts mt-3">
                    <h3>Follow Us</h3>
                    <div class="footer-social">
                        <a href="https://web.facebook.com/Wise-Life-Hacks-113283473860191"><i class="fa fa-facebook"></i></a>
                        <a href="https://twitter.com/QueenElizabet4"><i class="fa fa-twitter"></i></a>
                        <a href="https://www.linkedin.com/in/rhema-mensah-amoabeng-2130a61b8/"><i class="fa fa-linkedin"></i></a>
                        <a href="https://www.instagram.com/sandvetshops/?hl=en"><i class="fa fa-instagram"></i></a>
                    </div>
                </div>
            </div>  
            
            <div class="widget col-xl-3 col-sm-6 col-md-4">
                <div class="widget-footer-contacts">
                    <ul class="footer-list">
                        <li class=""><span class="value"><a href="{% url 'core:about' %}">About Us</a></span></li>
                    </ul>
                </div>
            </div>
            <div class="widget col-xl-3 col-sm-6 col-md-4">
                <div class="widget-footer-contacts">
                    <ul class="footer-list">
                        <li class=""><span class="value"><a href="{% url 'core:conditions' %}">Terms & Condition</a></span></li>
                    </ul>
                </div>
            </div>
            <div class="widget col-xl-3 col-sm-6 col-md-4">
                <div class="widget-footer-contacts">
                    <ul class="footer-list">
                        <li class=""><span class="value"><a href="{% url 'core:privacy-policy' %}">Privacy Policy</a></span></li>
                    </ul>
                </div>
            </div>
            <div class="widget col-xl-3 col-sm-6 col-md-4">
                <div class="widget-footer-contacts">
                    <ul class="footer-list">
                        <li class=""><span class="value"><a href="{% url 'core:return-policy' %}">Return Policy</a></span></li>
                    </ul>
                </div>
            </div>
            <div class="widget col-xl-3 col-sm-6 col-md-4">
                <div class="widget-footer-contacts">
                    <ul class="footer-list">
                        <li class=""><span class="value"><a href="{% url 'core:safety-tips' %}">Safety Tips </a></span></li>
                    </ul>
                </div>
            </div>
            <div class="widget col-xl-3 col-sm-6 col-md-4">
                <div class="widget-footer-contacts">
                    <ul class="footer-list">
                        <li class=""><span class="value"><a href="{% url 'core:faqs' %}">FAQs</a></span></li>
                    </ul>
                </div>
            </div>
            </div>

        </div>

        <div class="row hideLarge d-none">
            <div class="widget-footer-contacts col-12">
                <ul class="footer-list row">
                    <li class="col-xl-3 col-sm-6 col-md-4 col-6"><span class="value"><a href="{% url 'core:about' %}">About Us</a></li>
                    <li class="col-xl-3 col-sm-6 col-md-4 col-6"><span class="value"><a href="{% url 'core:contact' %}">Contact Us</a></li>
                    <li class="col-xl-3 col-sm-6 col-md-4 col-6"><span class="value"><a href="{% url 'core:conditions' %}">Terms & Conditions</a></li>
                    <li class="col-xl-3 col-sm-6 col-md-4 col-6"><span class="value"><a href="{% url 'core:privacy-policy' %}">Privacy Policy</a></li>
                    <li class="col-xl-3 col-sm-6 col-md-4 col-6"><span class="value"><a href="{% url 'core:return-policy' %}">Return Policy</a></li>
                    <li class="col-xl-3 col-sm-6 col-md-4 col-6"><span class="value"><a href="{% url 'core:safety-tips' %}">Safet Tips</a></li>
                    <li class="col-xl-3 col-sm-6 col-md-4 col-6"><span class="value"><a href="{% url 'core:faqs' %}">FAQs</a></li>
                    </ul>
                </div>
            </div>  
        </div>
    </div>
</section>
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="footer-content">
                    <div class="row justify-content-between">
                        <div class="col-xl-12">
                            <div class="copyright text-center">
                                <p><a href="tel://+233557566646">&copy; Sandvet, All Rights Reserved.</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

  <!-- Modal -->
  <div class="modal fade subscriptModal" id="subscriptionModal" tabindex="-1" aria-labelledby="subscriptionModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="subscriptionModalLabel">Property Alerts</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body form_subscription row">
            <div class="col-12 mb-2">
                <p>
                    Be the first to know about the best property deals in Ghana!
                </p>
            </div>
            <form action="" method="POST" class="col-12" id="subForm">
            <div id="signup_error"></div>
            <div class="row">
                {% csrf_token %} 
                <div class="col-12">
                    {{subscription_form|crispy}}
                </div>
            </div>
            <button type="submit"class="btn btn-primary col-12">Alert Me</button>
            </form>
            </div>
      </div>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade completeSubscriptModal" id="completeSubscriptionModal" tabindex="-1" aria-labelledby="completeSubscriptionModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="completeSubscriptionModalLabel">Thank your for subscribing</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <p>You will receive an update when this type of property becomes available.
                </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="col-12 btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

templates/includes/navbar.html
{% load static %}
<header>
    <div class="top__header">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="">
                    <div class="header__address">
                        <a href="tel://+233507321204">
                            <span><i class="fa fa-phone"></i>
                                +233507321204</span>
                        <a>                                   
                        <a href="{% url 'core:about' %}">
                            <span>About Us</span>
                        <a>   
                        <a href="{% url 'core:contact' %}" class="header__contact">
                            <span>Contact Us</span>
                        <a>   
                    </div>
                </div>
                <div class="">
                    <div class="header__social">
                        {% if request.user.is_authenticated %}
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{user.first_name}}<span class="caret"></span></a>
                            <ul class="dropdown-menu animated">
                                <li class=""><a href="#" class="dropdown-item">Dashboard</a></li>
                                <li class=""><a href="{% url 'account_logout' %}" class="dropdown-item">Logout</a></li>
                            </ul> 
                        {% else %}           
                        <a href="{% url 'account_login' %}">Login</i></a>              
                        <a href="{% url 'account_signup' %}">New Customer?</i></a>   
                        {% endif %}     
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="main__header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-brand m-0" href="{% url 'core:index' %}">
                        <img src="{% static 'img/core/logo.png' %}" alt="Sandvet Logo" class="img-fluid" width="200px" height="50px">
                    </a>
                    <button class="menu-button" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent">
                        <span class="icon-spar"></span>
                        <span class="icon-spar"></span>
                        <span class="icon-spar"></span>
                    </button>
        
                    <div class="navbar-collapse" id="navbarSupportedContent">
                        <div id="top-menu" class="d-inline my-2 my-lg-0 ml-auto">
                            <ul class="navbar-nav">
                                <!-- <li class="nav-item dropdown">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">For Rent<span class="caret"></span></a>
                                    <ul class="dropdown-menu animated">
                                        <li class="active"><a href="{% url 'property:for-rent' %}" class="dropdown-item">Properties For  Rent</a></li>
                                        <li class=""><a href="{% url 'cars:car-for-hire' %}" class="dropdown-item">Car For Hire</a></li>
                                        {% for cate in category_list_nav %}
                                            <li><a href="{{ cate.get_for_rent_category_url }}" class="dropdown-item"> {{cate.title}} for rent</a></li>
                                        {% endfor %}
                                    </ul>
                                </li> -->
                                <!-- <li class="nav-item dropdown ">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">For Sale<span class="caret"></span></a>
                                    <ul class="dropdown-menu animated">
                                        <li class="active"><a href="{% url 'property:for-sale' %}" class="dropdown-item">Properties For Sale</a></li>
                                        <li class=""><a href="{% url 'cars:car-for-sale' %}" class="dropdown-item">Cars for sale</a></li>
                                        <li class="active"><a href="{% url 'property:land' %}" class="dropdown-item">Land for Sale</a></li>
                                        {% for cate in category_list_nav %}
                                            <li><a href="{{ cate.get_for_sale_category_url }}" class="dropdown-item"> {{cate.title}} for sale</a></li>
                                        {% endfor %}
                                    </ul>
                                </li> -->
                                <!-- <li class="nav-item dropdown active">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cars<span class="caret"></span></a>
                                    <ul class="dropdown-menu animated">
                                        <li class="active"><a href="{% url 'cars:cars' %}" class="dropdown-item">Cars</a></li>
                                        <li class=""><a href="{% url 'cars:car-for-sale' %}" class="dropdown-item">For sale</a></li>
                                        <li class=""><a href="{% url 'cars:car-for-hire' %}" class="dropdown-item">For Hire</a></li>
                                        <li class=""><a href="{% url 'cars:spare-parts' %}" class="dropdown-item">Spare Parts</a></li>
                                        <li class=""><a href="{% url 'cars:schools' %}" class="dropdown-item">Driving School</a></li>
                                    </ul>
                                </li> -->
                                <li class="nav-item">
                                    <a href="{% url 'cars:cars' %}" class="nav-link ">Cars</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'cars:spare-parts' %}" class="nav-link ">Spare Parts</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'property:real-estates' %}" class="nav-link">Real Estates</a>
                                </li>
                                <!-- <li class="nav-item dropdown active">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hotels<span class="caret"></span></a>
                                    <ul class="dropdown-menu animated">
                                        <li class="active"><a href="{% url 'property:hotels' %}" class="dropdown-item">Hotels</a></li>
                                        <li class=""><a href="{% url 'property:hotel-rooms' %}" class="dropdown-item">Hotel Rooms</a></li>
                                    </ul>
                                </li> -->
                                <li class="nav-item">
                                    <a href="{% url 'property:hotels' %}" class="nav-link">Hotels</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'property:property' %}" class="nav-link">Property</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'property:land' %}" class="nav-link ">Land</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'cars:schools' %}" class="nav-link ">Driving Schools</a>
                                </li>
                                {% if request.user.is_authenticated %}
                                <li class="nav-item dropdown hidNav d-none">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">welcome {{user.first_name}}<span class="caret"></span></a>
                                    <ul class="dropdown-menu animated">
                                        {% if request.user.is_superuser %}
                                            <li class=""><a href="{% url 'dashboard:dashboard' %}" class="dropdown-item">Dashboard</a></li>
                                        {% endif %}
                                        <li class=""><a href="{% url 'account_logout' %}" class="dropdown-item">Logout</a></li>
                                        </ul>
                                    </li>
                                {%else%}
                                    <li class="nav-item hidNav d-none">
                                        <a href="{% url 'account_login' %}" class="nav-link ">Login</a>
                                    </li>
                                    <li class="nav-item hidNav d-none">
                                        <a href="{% url 'account_signup' %}" class="nav-link ">New Customer?</a>
                                    </li>
                                {%endif%}
                            </ul>
                        </div>
                        <a href="#" title="" class="close-menu"><i class="fa fa-close"></i></a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
  </header>