cars/urls.py
from django.urls import path
from . import views


app_name = 'cars'

urlpatterns = [
    path('', views.CarListView.as_view() , name='cars'),
    path('detail/<slug>/', views.CarDetail, name='car-detail'),
    path('brands/<slug>/', views.BrandListView.as_view(), name='brand'),
    path('brands/', views.BrandsView.as_view(), name='brands'),
    path('car/for-sale/', views.CarListSaleView.as_view(), name='car-for-sale'),
    path('for-hire/', views.CarListHireView.as_view(), name='car-for-hire'),
    path('spare-parts/', views.SparePartListView.as_view(), name='spare-parts'),
    path('spare-part/<slug>/', views.SparePartDetail, name='spare-part-detail'),
    path('driving-schools/', views.SchoolListView.as_view(), name='schools'),
    path('driving-school/<slug>/', views.SchoolDetail, name='school-detail'),
]

core/urls.py
from django.urls import path
from .views import *


app_name = 'core'

urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),

    path('category/<str:category>/', CategoryListView.as_view(), name='category'),
    path('locality/<str:locality>/', LocalityListView.as_view(), name='locality'),
    path('region/<str:region>/', RegionListView.as_view(), name='region'),
    path('search/', SearchBarListView.as_view(), name='search'),
    

    path('ajax_subscriptionform/', subscriptionForm),
    path('contact-us/', contactPage, name='contact'),
    path('about-us/', aboutPage, name='about'),
    path('terms-and-conditions/', ConditionPage, name='conditions'),
    path('privacy-policy/', PrivacyPolicyPage, name='privacy-policy'),
    path('return-policy/', ReturnPolicyPage, name='return-policy'),
    path('faqs/', FaqsPage, name='faqs'),
    path('safety-tips/', SafetyPage, name='safety-tips'),
]

property/urls.py
from django.urls import path
from .views import *


app_name = 'property'

urlpatterns = [
    path('', PropertyListView.as_view(), name='property'),
    path('for-sale/', ForSaleListView.as_view(), name='for-sale'),
    path('<slug>/for-sale/', CategoryForSaleListView.as_view(), name='for-sale-cate'),
    path('for-rent/', ForRentListView.as_view(), name='for-rent'),
    path('<slug>/for-rent/', CategoryForRentListView.as_view(), name='for-rent-cate'),

    path('detail/<slug>/', propertyDetail, name='property-detail'),


    path('search/', SearchListView.as_view(), name='search'),


    path('check/', checkPage, name='check'),

    path('land/', LandListView.as_view(), name='land'),

    path('real-estates/', RealEstateListView.as_view(), name='real-estates'),
    path('real-estate/detail/<slug>/', RealestateDetail, name='realestate-detail'),
    path('hotels/', HotelListView.as_view(), name='hotels'),
    path('hotel/detail/<slug>/', HotelDetail, name='hotel-detail'),
    path('hotel-rooms/', HotelRoomListView.as_view(), name='hotel-rooms'),
    path('hotel-room/detail/<slug>/', HotelRoomDetail, name='hotel-room-detail'),
]

sandvet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('property/', include('property.urls', namespace='property')),
    path('cars/', include('cars.urls', namespace='cars')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/models.py
from colorfield.fields import ColorField
from datetime import datetime, date
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import gettext as _
from django.shortcuts import reverse
from autoslug import AutoSlugField
from autoslug.settings import slugify as default_slugify
from core.models import Region, Locality, REGIONS_LIST, Booking
# Create your models here.

def custom_slugify(value):
    return default_slugify(value).replace(' ', '-')

def year_choices():
    return [(r,r) for r in range(1984, date.today().year+1)]

def current_year():
    return date.today().year

def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)    


CARE_PURPOSE_TYPE = [
    ('sale', 'Sale'),
    ('hire', 'Hire'),
]

CAR_STATE = [
    ('new', 'New'),
    ('used', 'Used'),
]

CAR_DRIVE_TYPE = [
    ('left', 'Left'),
    ('right', 'Right'),
]

CAR_AIR_CON = [
    ('no', 'No'),
    ('yes', 'Yes'),
]

CAR_GEARBOX = [
    ('automatic', 'Automatic'),
    ('manual', 'Manual'),
]

CAR_FUEL_TYPE = [
    ('petrol', 'Petrol'),
    ('diesel', 'Diesel'),
    ('gas', 'Gas'),
]


class Type(models.Model):
    name = models.CharField(unique=True, max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(populate_from='name', unique_with='created_at__month', slugify=custom_slugify )
    
    def __str__(self):
        return self.name

    
    

class Brand(models.Model):
    name = models.CharField(unique=True, max_length=200)
    featured = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='brands/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0)
    slug = AutoSlugField(populate_from='name', unique_with='created_at__month', slugify=custom_slugify )

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url 
        except:
            url = ''
        return url
    
    def get_absolute_url(self):
        return reverse("cars:brand", kwargs={
            'slug': self.slug
        })


class Car(models.Model):
    title = models.CharField(max_length=200,null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='cars/')
    description = models.TextField(null=True, blank=False)
    views = models.PositiveIntegerField(default=0)
    featured = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(populate_from='title',unique_with='created_at__month',slugify=custom_slugify )
    region = models.CharField(max_length=20, choices=REGIONS_LIST, null=True, blank=True)
    # #######
    
    purpose = models.CharField(max_length=4, choices=CARE_PURPOSE_TYPE, null=True, blank=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True, blank=True, related_name='carbrands')
    locality = models.ForeignKey(Locality, on_delete=models.SET_NULL, null=True, blank=True, related_name='carlocality')
    car_type = models.ForeignKey(Type, on_delete=models.SET_NULL, null=True, blank=True, related_name='cartypes')
    int_color = ColorField(default="#FFFFFF", null=True, blank=True)
    ext_color = ColorField(default="#FFFFFF", null=True, blank=True)
    mileage = models.CharField(max_length=200, null=True, blank=True)
    fuel_type = models.CharField(max_length=6, choices=CAR_FUEL_TYPE, null=True, blank=True)
    gearbox = models.CharField(max_length=10, choices=CAR_GEARBOX, null=True, blank=True)
    drive_type = models.CharField(max_length=5, choices=CAR_DRIVE_TYPE, null=True, blank=True)
    car_state = models.CharField(max_length=4, choices=CAR_STATE, null=True)
    engine = models.CharField(max_length=200, null=True, blank=True)
    air_con = models.CharField(max_length=3, choices=CAR_AIR_CON, null=True, blank=True)
    year = models.IntegerField(_('year'), validators=[MinValueValidator(1984), max_value_current_year])

    def __str__(self):
        return self.title

    @property
    def imageURL(self):
        try:
            url = self.image.url 
        except:
            url = ''
        return url

    def get_absolute_url(self):
        return reverse("cars:car-detail", kwargs={
            'slug': self.slug
        })

    def get_date(self):
        time = datetime.now()
        if self.created_at.day == time.day:
            return str(time.hour - self.created_at.hour) + " hours ago"
        else:
            if self.created_at.month == time.month:
                return str(time.day - self.created_at.day) + " days ago"
            else:
                if self.created_at.year == time.year:
                    return str(time.month - self.created_at.month) + " months ago"
                else:
                    return str(time.year - self.created_at.year) + " year(s) ago"
        return self.created_at



class CarImage(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, null=True, blank=True, related_name='carimages')
    images = models.ImageField(null=True, blank=True, upload_to="cars")

    def __str__(self):
        return self.car.title

    @property
    def imageURL(self):
        try:
            url = self.images.url 
        except:
            url = ''
        return url





class SparePart(models.Model):
    title = models.CharField(max_length=200,null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='spareparts/')
    description = models.TextField(null=True, blank=False)
    views = models.PositiveIntegerField(default=0)
    featured = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(populate_from='title',unique_with='created_at__month',slugify=custom_slugify )
    region = models.CharField(max_length=20, choices=REGIONS_LIST, null=True, blank=True)
    locality = models.ForeignKey(Locality, on_delete=models.SET_NULL, null=True, blank=True, related_name='sparelocality')
    condition = models.CharField(max_length=4, choices=CAR_STATE, null=True)

    def __str__(self):
        return self.title

    @property
    def imageURL(self):
        try:
            url = self.image.url 
        except:
            url = ''
        return url
    
    def get_absolute_url(self):
        return reverse("cars:spare-part-detail", kwargs={
            'slug': self.slug
        })

    def get_date(self):
        time = datetime.now()
        if self.created_at.day == time.day:
            return str(time.hour - self.created_at.hour) + " hours ago"
        else:
            if self.created_at.month == time.month:
                return str(time.day - self.created_at.day) + " days ago"
            else:
                if self.created_at.year == time.year:
                    return str(time.month - self.created_at.month) + " months ago"
                else:
                    return str(time.year - self.created_at.year) + " year(s) ago"
        return self.created_at



class SparePartImage(models.Model):
    sparepart = models.ForeignKey(SparePart, on_delete=models.CASCADE, null=True, blank=True, related_name="sparepartimages")
    images = models.ImageField(null=True, blank=True, upload_to="cars/spareparts")

    def __str__(self):
        return self.sparepart.title

    @property
    def imageURL(self):
        try:
            url = self.images.url 
        except:
            url = ''
        return url






class School(models.Model):
    title = models.CharField(max_length=200,null=True)
    region = models.CharField(max_length=20, choices=REGIONS_LIST, null=True, blank=True)
    locality = models.ForeignKey(Locality, on_delete=models.SET_NULL, null=True, blank=True, related_name='schoollocality')
    image = models.ImageField(upload_to='school/')
    description = models.TextField(null=True, blank=False)
    location = models.CharField(max_length=20, null=True, blank=True)
    views = models.PositiveIntegerField(default=0)
    featured = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(populate_from='title',unique_with='created_at__month',slugify=custom_slugify )

    def __str__(self):
        return self.title

    @property
    def imageURL(self):
        try:
            url = self.image.url 
        except:
            url = ''
        return url
    
    def get_absolute_url(self):
        return reverse("cars:school-detail", kwargs={
            'slug': self.slug
        })
    
    def get_date(self):
        time = datetime.now()
        if self.created_at.day == time.day:
            return str(time.hour - self.created_at.hour) + " hours ago"
        else:
            if self.created_at.month == time.month:
                return str(time.day - self.created_at.day) + " days ago"
            else:
                if self.created_at.year == time.year:
                    return str(time.month - self.created_at.month) + " months ago"
                else:
                    return str(time.year - self.created_at.year) + " year(s) ago"
        return self.created_at

    
class SchoolImage(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE, null=True, blank=True, related_name="schoolimage")
    images = models.ImageField(null=True, blank=True, upload_to="cars/school")

    def __str__(self):
        return self.sparepart.title

    @property
    def imageURL(self):
        try:
            url = self.images.url 
        except:
            url = ''
        return url













class CarBooking(models.Model):
    booking = models.OneToOneField(Booking,  on_delete=models.CASCADE, related_name='carbooking', null=True)
    car = models.ForeignKey(Car,  on_delete=models.CASCADE, related_name='bookcar', null=True)

templates/includes/index/bannerSlider.html
{% load crispy_forms_tags %} 
{% load static %}


<section class="banner-partial banner-brands hideLarge d-none" style="background-image: url({% static 'img/core/banner-realestate.jpg' %});">
    <div class="container">
        <di class="row">
            <div class="col-md-12">
                <div class="widget-property-search card home-widget-search">
                    <form action="{% url 'core:search' %}" method="GET">
                        <div class="row justify-content-center align-items-center">
                            <div class="col-11">
                                <div class="row ">
                                    <div class="col-4 border-col">
                                        <div id="div_id_region" class="form-group">
                                            <div class="">
                                                <select name="categories" class="select form-control" id="id_region" tabindex="-1">
                                                    <option value="property">Property</option>
                                                    <option value="cars">Cars</option>
                                                    <option value="spareparts">Spare Parts</option>
                                                    <option value="realestates">Real Estates</option>
                                                    <option value="hotels">Hotel</option>
                                                    <option value="hotelrooms">Hotel Rooms</option>
                                                    <option value="lands">Land</option>
                                                    <option value="schools">Driving Schools</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-8 border-col">
                                        <div id="div_id_title" class="form-group">
                                            <div class="">
                                                <input type="text" name="search-title" class="textinput textInput form-control" id="id_title" placeholder="Search by Title or Name" required>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary  btn-search"><i class="fa fa-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </di>
    </div>
</section>
<section class="main-banner-sec hideView">
    <div class="banner-carousel">
        <div class="banner-slide" style="background-image: url({% static 'img/core/banner-realestate.jpg' %});">
            <div class="home-banner-section col-12">
                <h3 class="text-center">Buy Properties from the Best Developers.</h3>
                <div class="widget-property-search card mt-3 home-widget-search col-11 mx-auto">
                    <form action="{% url 'property:real-estates' %}" class="realestateForm">
                        <div class="row justify-content-center">
                            <div class="col-lg-11 col-12">
                                <div class="row ">
                                    {% for field in realestatefilter.form %}
                                    <div class="col-lg-3 border-col">
                                        {{ field|as_crispy_field }}
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary  btn-search"><i class="fa fa-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="banner-slide" style="background-image: url({% static 'img/core/banner-hotel.jpg' %});">
            <div class="home-banner-section col-12">
                <h3 class="text-center">Book your desired Hotel with us.</h3>
                <div class="widget-property-search card mt-3 home-widget-search col-11 mx-auto">
                    <form action="{% url 'property:hotels' %}" class="hotelForm">
                        <div class="row justify-content-center">
                            <div class="col-lg-11 col-12">
                                <div class="row ">
                                    {% for field in hotelfilter.form %}
                                    <div class="col-lg-3 border-col">
                                        {{ field|as_crispy_field }}
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary  btn-search"><i class="fa fa-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="banner-slide" style="background-image: url({% static 'img/about/carousel-3.jpg' %});">
            <div class="home-banner-section col-12">
                <h3 class="text-center">Discover a home you'll love to stay</h3>
                <div class="widget-property-search card mt-3 home-widget-search col-11 mx-auto">
                    <form action="{% url 'property:search' %}" class="">
                        <div class="row justify-content-center">
                            <div class="col-lg-11 col-12">
                                <div class="row ">
                                    {% for field in filter.form %}
                                    <div class="col-lg-3 border-col">
                                        {{ field|as_crispy_field }}
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary  btn-search"><i class="fa fa-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="banner-slide" style="background-image: url({% static 'img/about/carousel-4.jpg' %});">
            <div class="home-banner-section col-12">
                <h3 class="text-center">Find your dream car with us.</h3>
                <!-- <p class="text-center">Best automobile market hub in Ghana.</p> -->
                <div class="widget-property-search card mt-3 home-widget-search col-11 mx-auto">
                    <form action="{% url 'cars:cars' %}" class="banner-cars">
                        <div class="row justify-content-center">
                            <div class="col-lg-11 col-12">
                                <div class="row ">
                                    {% for field in carfilter.form %}
                                    <div class="col-lg-3 border-col">
                                        {{ field|as_crispy_field }}
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary  btn-search"><i class="fa fa-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="banner-slide" style="background-image: url({% static 'img/core/banner-car-parts1.jpg' %});">
            <div class="home-banner-section col-12">
                <h3 class="text-center">Best Car Spare parts in Ghana</h3>
                <!-- <p class="text-center">Best automobile market hub in Ghana.</p> -->
                <div class="widget-property-search card mt-3 home-widget-search col-11 mx-auto">
                    <form action="{% url 'cars:spare-parts' %}" class="banner-cars sparepartForm">
                        <div class="row justify-content-center">
                            <div class="col-lg-11 col-12">
                                <div class="row ">
                                    {% for field in sparepartfilter.form %}
                                    <div class="col-lg-3 border-col">
                                        {{ field|as_crispy_field }}
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary  btn-search"><i class="fa fa-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

templates/includes/index/car-brands.html
{% load humanize %}
{% load static %}
{% if  brands %}
    <section class="popular-listing py-4  section-popular-listings">
        <div class="container">
            <div class="row align-items-center justify-content-between panel__cardhead">
                <div class="pannel__headtitle">
                    <h2>Top Car Brands</h2>
                </div>
                <div class="nav nav-tabs">
                    <li class="nav-item"><button id="pannelPrevBrands" class="nav-link btnArrows mr-1"> <i class="fa fa-angle-left"></i> </button></li>
                    <li class="nav-item"><button id="pannelNextBrands" class="btnArrows nav-link"> <i class="fa fa-angle-right"></i></button></li>
                </div>
            </div>
                
            <div id="panel__responsiveBrands" class="row panel__responsive panel__cardbody align-items-center">
                {% for list in brands %}
                <div class="mx-3">
                    <div class="card text-center listing__card brand-card">
                        <div class="brand-img">
                            <img data-src="{{ list.imageURL }}" src="{% static 'img/core/placeholder.jpg' %}" alt="{{ list.name }}" class="img-fluid lozad">
                        </div>
                        <div class="brand-title">
                            <a href="{{list.get_absolute_url}}">{{ list.name }}</a>
                        </div>
                        <a href="{{list.get_absolute_url}}" title="{{ list.name }}" class="ext-link" tabindex="0"></a>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="row align-items-center justify-content-center panel__cardfooter">
                <a href="{% url 'cars:brands' %}" class="btn btn-see-more">view all brands</a>
            </div> 
        </div>
    </section>
    <script>$(document).ready(function() {"use strict";$('#panel__responsiveBrands').slick({autoplay: true,autoplaySpeed: 2000,dots: false,infinite: true,speed: 300,slidesToShow: 7,slidesToScroll: 7,prevArrow: $('#pannelPrevBrands'),nextArrow: $('#pannelNextBrands'),responsive: [{breakpoint: 1024,settings: {slidesToShow: 3,slidesToScroll: 3,infinite: true,dots: true}},{breakpoint: 754,settings: {slidesToShow: 2,slidesToScroll: 2}},{breakpoint: 480,settings: {slidesToShow: 1,slidesToScroll: 1}}]});})</script>
{% endif %}

templates/includes/index/hideview.html
{% load static %}
<section class="popular-listing  section-popular-listings mb-5 hideLarge d-none">
    <div class="container-fluid panel__cardbody px-5">
        <div class="row align-items-center justify-content-between panel__cardhead">
            <div class="pannel__headtitle">
                <h2 class="text-right">Cars</h2>
            </div>
            <div class="nav nav-tabs">
                <li class="nav-item"><button id="pannelPrevsect1" class="nav-link btnArrows mr-1"> <i class="fa fa-angle-left"></i> </button></li>
                <li class="nav-item"><button id="pannelNextsect1" class="btnArrows nav-link"> <i class="fa fa-angle-right"></i></button></li>
            </div>
        </div>
        <div id="panel__responsivesect1" class="row panel__responsive  align-items-center pt-3 mb-1 ">
            <div class="mx-3">
                <div class="card text-center listing__card brand-card p-0">
                    <div class="brand-img">
                        <a href="{% url 'cars:cars' %}"><img data-src="{% static 'img/about/carousel-4.jpg' %}" src="{% static 'img/core/placeholder.jpg' %}" alt="#" class="img-fluid lozad"></a>
                    </div>
                    <div class="brand-title">
                        <a href="{% url 'cars:cars' %}">Cars</a>
                    </div>
                    <a href="{% url 'cars:cars' %}" title="" class="ext-link" tabindex="0"></a>
                </div>
            </div>
            <div class="mx-3">
                <div class="card text-center listing__card brand-card p-0">
                    <div class="brand-img">
                        <a href="{% url 'cars:spare-parts' %}"><img data-src="{% static 'img/core/banner-car-parts1.jpg' %}" src="{% static 'img/core/placeholder.jpg' %}" alt="#" class="img-fluid lozad"></a>
                    </div>
                    <div class="brand-title">
                        <a href="{% url 'cars:spare-parts' %}">Spare Parts</a>
                    </div>
                    <a href="{% url 'cars:spare-parts' %}" title="" class="ext-link" tabindex="0"></a>
                </div>
            </div>
            <div class="mx-3">
                <div class="card text-center listing__card brand-card p-0">
                    <div class="brand-img">
                        <a href="{% url 'cars:schools' %}"><img data-src="{% static 'img/core/driving-school.jpg' %}" src="{% static 'img/core/placeholder.jpg' %}" alt="#" class="img-fluid lozad"></a>
                    </div>
                    <div class="brand-title">
                        <a href="{% url 'cars:schools' %}">Driving Schools</a>
                    </div>
                    <a href="{% url 'cars:schools' %}" title="" class="ext-link" tabindex="0"></a>
                </div>
            </div>
            <div class="mx-3">
                <div class="card text-center listing__card brand-card p-0">
                    <div class="brand-img">
                        <a href="{% url 'cars:brands' %}"><img data-src="{% static 'img/core/car-brands.jpg' %}" src="{% static 'img/core/placeholder.jpg' %}" alt="#" class="img-fluid lozad"></a>
                    </div>
                    <div class="brand-title">
                        <a href="{% url 'cars:brands' %}">Car Brands</a>
                    </div>
                    <a href="{% url 'cars:brands' %}" title="" class="ext-link" tabindex="0"></a>
                </div>
            </div>
        </div>
    </div>
</section>
<script>$(document).ready(function() {"use strict";$('#panel__responsivesect1').slick({autoplay: true,autoplaySpeed: 2000,dots: true,infinite: true,speed: 300,slidesToShow: 8,slidesToScroll: 8,prevArrow: $('#pannelPrevsect1'),nextArrow: $('#pannelNextsect1'),responsive: [{breakpoint: 1024,settings: {slidesToShow: 3,slidesToScroll: 3,infinite: true,dots: true}},{breakpoint: 754,settings: {slidesToShow: 2,slidesToScroll: 2}},{breakpoint: 480,settings: {slidesToShow: 1,slidesToScroll: 1}}]});})</script>

templates/includes/index/partners.html
{% load humanize %}
{% load static %}
{% if  partners %}
    <section class="popular-listing  section-popular-listings mb-5">
        <div class="container-fluid panel__cardbody px-5">
            <div class="row">
                <div class="col-12 pannel__headtitle">
                    <h2 class="text-center">Trusted Partners</h2>
                </div>
            </div>
            <div id="panel__responsivePertners" class="row panel__responsive  align-items-center pt-3 mb-1">
                {% for list in partners %}
                    <div class="mx-3">
                        <div class="card text-center listing__card brand-card">
                            {% if 'http' in list.3 %}
                                <div class="brand-img">
                                    <a href="{% url 'property:realestate-detail' slug=list.1%}"><img data-src="/media/{{ list.2 }}" src="{% static 'img/core/placeholder.jpg' %}" alt="{{ list.0 }}" class="img-fluid lozad"></a>
                                </div>
                                <a href="{% url 'property:realestate-detail' slug=list.1%}" title="{{ list.0 }}" class="ext-link" tabindex="0"></a>
                            {% else %}
                                <div class="brand-img">
                                    <a href="{% url 'property:hotel-detail' slug=list.1%}"><img data-src="/media/{{ list.2 }}" src="{% static 'img/core/placeholder.jpg' %}" alt="{{ list.0 }}" class="img-fluid lozad"></a>
                                </div>
                                <a href="{% url 'property:hotel-detail' slug=list.1%}" title="{{ list.0 }}" class="ext-link" tabindex="0"></a>
                            {% endif %}
                        </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <script>$(document).ready(function() {"use strict";$('#panel__responsivePertners').slick({autoplay: true,autoplaySpeed: 2000,dots: true,infinite: true,speed: 300,slidesToShow: 8,slidesToScroll: 8,prevArrow: $('#pannelPrevPartners'),nextArrow: $('#pannelNextPartners'),responsive: [{breakpoint: 1024,settings: {slidesToShow: 3,slidesToScroll: 3,infinite: true,dots: true}},{breakpoint: 754,settings: {slidesToShow: 2,slidesToScroll: 2}},{breakpoint: 480,settings: {slidesToShow: 1,slidesToScroll: 1}}]});})</script>
{% endif %}