cars/urls.py
from django.urls import path
from . import views


app_name = 'cars'

urlpatterns = [
    path('', views.CarListView.as_view() , name='cars'),
    path('detail/<slug>/', views.CarDetail, name='car-detail'),
    path('brands/<slug>/', views.BrandListView.as_view(), name='brand'),
    path('brands/', views.BrandsView.as_view(), name='brands'),
    path('car/for-sale/', views.CarListSaleView.as_view(), name='car-for-sale'),
    path('for-hire/', views.CarListHireView.as_view(), name='car-for-hire'),
    path('spare-parts/', views.SparePartListView.as_view(), name='spare-parts'),
    path('spare-part/<slug>/', views.SparePartDetail, name='spare-part-detail'),
    path('driving-schools/', views.SchoolListView.as_view(), name='schools'),
    path('driving-school/<slug>/', views.SchoolDetail, name='school-detail'),
]

dashboard/urls.py
from django.urls import path
from .views import core, prop, cars

app_name = 'dashboard'

urlpatterns = [
    path("accounts/auth/", core.auth, name="auth"),

    path('', core.dashboardPage, name='dashboard'),
    path('locality/', core.LocalityPage, name='locality'),
    path('locality/add/', core.LocalityAddPage, name='locality-add'),
    path('locality/<int:id>/edit/', core.LocalityEditPage, name='edit-locality'),
    path('locality/<int:id>/delete/', core.DeleteLocality, name='delete-locality'),

    # Bookings
    path('bookings/', core.BookingsPage, name='bookings'),
    path('booking/<int:id>/view/', core.ViewBooking, name='view-booking'),
    path('booking/<int:id>/delete/', core.DeleteBooking, name='delete-booking'),

    path('bookings/cars/', core.CarBookingsPage, name='car-bookings'),
    path('bookings/spareparts/', core.SparePartBookingsPage, name='sparepart-bookings'),
    path('bookings/driving-school/', core.SchoolBookingsPage, name='school-bookings'),
    path('bookings/properties/', core.PropertyBookingsPage, name='properties-bookings'),
    path('bookings/hotels/', core.HotelBookingsPage, name='hotels-bookings'),
    path('bookings/hotel-rooms/', core.HotelRoomBookingsPage, name='hotelrooms-bookings'),
    path('bookings/real-estates/', core.RealEstateBookingsPage, name='realestates-bookings'),

    # Propery
    path('properties/', prop.propertyPage, name='property'),
    path('property/add/', prop.PropertyAddPage, name='add-property'),
    path('property/<int:id>/edit/', prop.PropertyEditPage, name='edit-property'),
    path('property/<int:id>/view/', prop.ViewProperty, name='view-property'),
    path('property/<int:id>/delete/', prop.DeleteProperty, name='delete-property'),
    path('property/image/<int:id>/delete/', prop.DeletePropertyImage, name='delete-property-image'),

    # Property Category
    path('property/categories/', prop.CategoryPage, name='categories'),
    path('property/category/add/', prop.CategoryAddPage, name='add-category'),
    path('property/category/<int:id>/edit/', prop.CategoryEditPage, name='edit-category'),
    path('property/category/<int:id>/delete/', prop.DeleteCategory, name='delete-category'),

    # Real Estate
    path('real-estates/', prop.RealEstatePage, name='realestates'),
    path('real-estate/add/', prop.RealEstateAddPage, name='add-realestate'),
    path('real-estate/<int:id>/view/', prop.ViewRealEstate, name='view-realestate'),
    path('real-estate/<int:id>/edit/', prop.RealEstateEditPage, name='edit-realestate'),
    path('real-estate/<int:id>/delete/', prop.DeleteRealEstate, name='delete-realestate'),
    path('real-estate/<int:id>/featured/', prop.FeaturedRealEstate, name='featured-realestate'),
    path('real-estate/image/<int:id>/delete/', prop.DeleteRealEstateImage, name='delete-realestate-image'),

    # Hotels
    path('hotels/', prop.HotelsPage, name='hotels'),
    path('hotel/add/', prop.HotelAddPage, name='add-hotel'),
    path('hotel/<int:id>/view/', prop.ViewHotel, name='view-hotel'),
    path('hotel/<int:id>/featured/', prop.FeaturedHotel, name='featured-hotel'),
    path('hotel/<int:id>/edit/', prop.HotelEditPage, name='edit-hotel'),
    path('hotel/<int:id>/delete/', prop.DeleteHotel, name='delete-hotel'),
    path('hotel/image/<int:id>/delete/', prop.DeleteHotelImage, name='delete-hotel-image'),

    # Hotels Room
    path('hotel-rooms/', prop.HotelRoomsPage, name='hotel-rooms'),
    path('hotel-room/add/', prop.HotelRoomAddPage, name='add-hotel-room'),
    path('hotel-room/<int:id>/view/', prop.ViewHotelRoom, name='view-hotel-room'),
    path('hotel-room/<int:id>/edit/', prop.HotelRoomEditPage, name='edit-hotel-room'),
    path('hotel-room/<int:id>/featured/', prop.FeaturedHotelRoom, name='featured-hotel-room'),
    path('hotel-room/<int:id>/delete/', prop.DeleteHotelRoom, name='delete-hotel-room'),
    path('hotel-room/image/<int:id>/delete/', prop.DeleteHotelRoomImage, name='delete-hotel-room-image'),

    # Cars
    path('cars/', cars.CarPage, name='car'),
    path('car/add/', cars.CarAddPage, name='add-car'),
    path('car/<int:id>/delete/', cars.DeleteCar, name='delete-car'),
    path('car/<int:id>/edit/', cars.CarEditPage, name='edit-car'),
    path('car/<int:id>/view/', cars.ViewCar, name='view-car'),
    path('car/image/<int:id>/delete/', cars.DeleteCarImage, name='delete-car-image'),
    path('car/<int:id>/featured/', cars.FeaturedCar, name='featured-car'),

    path('brands/', cars.BrandPage, name='brands'),
    path('brand/add/', cars.BrandAddPage, name='add-brand'),
    path('brand/<int:id>/featured/', cars.FeaturedBrand, name='featured-brand'),
    path('brand/<int:id>/view/', cars.ViewBrand, name='view-brand'),
    path('brand/<int:id>/delete/', cars.DeleteBrand, name='delete-brand'),
    path('brand/<int:id>/edit/', cars.BrandEditPage, name='edit-brand'),
    
    path('car/types/', cars.TypePage, name='types'),
    path('car/type/add/', cars.TypeAddPage, name='add-type'),
    path('car/type/<int:id>/edit/', cars.TypeEditPage, name='edit-type'),
    path('car/type/<int:id>/delete/', cars.DeleteType, name='delete-type'),

    # SPARE PARTS
    path('car/spare-parts/', cars.SparePartPage, name='spare-parts'),
    path('car/spare-part/add/', cars.SparePartAddPage, name='add-spare-part'),
    path('car/spare-part/<int:id>/Edit/', cars.SparePartEditPage, name='edit-spare-part'),
    path('car/spare-part/<int:id>/view/', cars.ViewSparePart, name='view-spare-part'),
    path('car/spare-part/<int:id>/featured/', cars.FeaturedSparePart, name='featured-spare-part'),
    path('car/spare-part/<int:id>/delete/', cars.DeleteSparePart, name='delete-spare-part'),
    path('car/spare-part/image/<int:id>/delete/', cars.DeleteSparePartImage, name='delete-sparepart-image'),
    
    # DRIVING SCHOOL
    path('car/driving-schools/', cars.SchoolPage, name='schools'),
    path('car/driving-school/add/', cars.SchoolAddPage, name='add-school'),
    path('car/driving-school/<int:id>/Edit/', cars.SchoolEditPage, name='edit-school'),
    path('car/driving-school/<int:id>/view/', cars.ViewSchool, name='view-school'),
    path('car/driving-school/<int:id>/featured/', cars.FeaturedSchool, name='featured-school'),
    path('car/driving-school/<int:id>/delete/', cars.DeleteSchool, name='delete-school'),
    path('car/driving-school/image/<int:id>/delete/', cars.DeleteSchoolImage, name='delete-school-image'),

    # Ajax URLS
    path("dashboard/property/add/land/", prop.ajaxPropertyLandAdd, name="add-land-property"),
    path("dashboard/property/add/house/", prop.ajaxPropertyHouseAdd, name="add-house-property"),
    path("dashboard/logout/", core.authLogout, name="logout"),

]

property/urls.py
from django.urls import path
from .views import *


app_name = 'property'

urlpatterns = [
    path('', PropertyListView.as_view(), name='property'),
    path('for-sale/', ForSaleListView.as_view(), name='for-sale'),
    path('<slug>/for-sale/', CategoryForSaleListView.as_view(), name='for-sale-cate'),
    path('for-rent/', ForRentListView.as_view(), name='for-rent'),
    path('<slug>/for-rent/', CategoryForRentListView.as_view(), name='for-rent-cate'),

    path('detail/<slug>/', propertyDetail, name='property-detail'),


    path('search/', SearchListView.as_view(), name='search'),


    path('check/', checkPage, name='check'),

    path('land/', LandListView.as_view(), name='land'),

    path('real-estates/', RealEstateListView.as_view(), name='real-estates'),
    path('real-estate/detail/<slug>/', RealestateDetail, name='realestate-detail'),
    path('hotels/', HotelListView.as_view(), name='hotels'),
    path('hotel/detail/<slug>/', HotelDetail, name='hotel-detail'),
    path('hotel-rooms/', HotelRoomListView.as_view(), name='hotel-rooms'),
    path('hotel-room/detail/<slug>/', HotelRoomDetail, name='hotel-room-detail'),
]

sandvet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('property/', include('property.urls', namespace='property')),
    path('cars/', include('cars.urls', namespace='cars')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

property/forms.py
from django import forms

dashboard/views/core.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db.models import Count, Q
from django.contrib.auth import  logout
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from property.models import Property, LandProperty, HouseProperty, PropertyBooking, HotelBooking, RealEstateBooking, HotelRoomBooking
from core.models import Locality, Booking
from dashboard.forms import PropertyForm, PropertyLandForm, CarForm, CarImagesForm, BrandForm, TypeForm, SparePartForm, SparePartImagesForm, SchoolForm, SchoolImagesForm, LocalityForm
from cars.models import CarImage, Car, Brand, Type, School, SparePart, SparePartImage, School, SchoolImage, CarBooking, SchoolBooking, SparePartBooking
from dashboard.decorators import check_admin
# Create your views here.
def gen_asset_id(moduleName):
    moduleInstance = moduleName.objects.last()
    if moduleInstance is not None:
        return (moduleInstance.id + 1)
    return 1

@login_required
def authLogout(request):
    logout(request)
    messages.success(request, "You have signed out.")
    return redirect('account_login')

def auth(request):
    if request.user.is_superuser:
        return redirect(reverse("dashboard:dashboard"), permanent=True)
    else:
        return redirect(reverse("core:index"), permanent=True)



@login_required
@check_admin
def dashboardPage(request):
    user_count = User.objects.filter(~Q(is_superuser=True)).count()
    bookings = Booking.objects.filter(read=False).order_by('-id')[:10]
    context = {
        'dash_title': 'Dashboard',
        'bookings': bookings,
        "user_count": user_count,
    }
    return render(request, 'dashboard/index.html', context)


@login_required
@check_admin
def LocalityPage(request):
    locality = Locality.objects.all()
    context = {
        'dash_title': 'Locality',
        'locality_list': locality
    }
    return render(request, 'dashboard/locality.html', context)


@login_required
@check_admin
def LocalityAddPage(request):
    form = LocalityForm()
    if request.method == "POST":
        form = LocalityForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Locality  been Added succesfully')
            return redirect('dashboard:locality')
        else:
            print(form.errors)
    context = {
        "dash_title": 'Add Locality',
        "form": form,
    }
    return render(request, "dashboard/add-locality.html", context)


@login_required
@check_admin
def DeleteLocality(request, *args, **kwargs):
    get_object_or_404(Locality, pk=kwargs["id"]).delete()
    messages.success(request, "Locality deleted successfully")
    return redirect(reverse("dashboard:locality"))




@login_required
@check_admin
def LocalityEditPage(request, *args, **kwargs):
    locality = get_object_or_404(Locality, pk=kwargs["id"])
    form = LocalityForm(instance=locality)
    if request.method == "POST":
        form = LocalityForm(request.POST, instance=locality)
        if form.is_valid():
            form.save()
            messages.success(request, 'Locality  been updated succesfully')
            return redirect('dashboard:locality')
        else:
            print(form.errors)
    context = {
        "dash_title": 'Edit Locality',
        "form": form,
    }
    return render(request, "dashboard/edit-locality.html", context)




@login_required
@check_admin
def BookingsPage(request):
    bookings = Booking.objects.order_by('-id')
    context = {
        'dash_title': 'Bookings',
        'bookings': bookings
    }
    return render(request, 'dashboard/bookings.html', context)


@login_required
@check_admin
def DeleteBooking(request, *args, **kwargs):
    get_object_or_404(Booking, pk=kwargs["id"]).delete()
    messages.success(request, "Booking deleted successfully")
    return redirect(reverse("dashboard:bookings"))


@login_required
@check_admin
def ViewBooking(request, *args, **kwargs):
    booking = get_object_or_404(Booking, pk=kwargs["id"])

    booking.read = True
    booking.save()

    context = {
        'dash_title': 'View Bookings',
        "booking": booking,
    }
    return render(request, "dashboard/view-booking.html", context)





@login_required
@check_admin
def CarBookingsPage(request):
    bookings = CarBooking.objects.order_by('-id')
    context = {
        'dash_title': 'Car Bookings',
        'bookings': bookings
    }
    return render(request, 'dashboard/ind-bookings.html', context)


@login_required
@check_admin
def SparePartBookingsPage(request):
    bookings = SparePartBooking.objects.order_by('-id')
    context = {
        'dash_title': 'Spare Parts Bookings',
        'bookings': bookings
    }
    return render(request, 'dashboard/ind-bookings.html', context)


@login_required
@check_admin
def SchoolBookingsPage(request):
    bookings = SchoolBooking.objects.order_by('-id')
    context = {
        'dash_title': 'School Bookings',
        'bookings': bookings
    }
    return render(request, 'dashboard/ind-bookings.html', context)


@login_required
@check_admin
def PropertyBookingsPage(request):
    bookings = PropertyBooking.objects.order_by('-id')
    context = {
        'dash_title': 'Property Bookings',
        'bookings': bookings
    }
    return render(request, 'dashboard/ind-bookings.html', context)

@login_required
@check_admin
def HotelBookingsPage(request):
    bookings = HotelBooking.objects.order_by('-id')
    context = {
        'dash_title': 'Hotel Bookings',
        'bookings': bookings
    }
    return render(request, 'dashboard/ind-bookings.html', context)

@login_required
@check_admin
def RealEstateBookingsPage(request):
    bookings = RealEstateBooking.objects.order_by('-id')
    context = {
        'dash_title': 'Real Estate Bookings',
        'bookings': bookings
    }
    return render(request, 'dashboard/ind-bookings.html', context)

@login_required
@check_admin
def HotelRoomBookingsPage(request):
    bookings = HotelRoomBooking.objects.order_by('-id')
    context = {
        'dash_title': 'Hotel Room Bookings',
        'bookings': bookings
    }
    return render(request, 'dashboard/ind-bookings.html', context)

dashboard/templates/dashboard/add-hotel-room.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %} 
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-12"> 
        <div class="card">
            <div class="card-body">
                <a href="{% url 'dashboard:hotel-rooms' %}" class="btn btn-primary mb-3"> <i class="mdi mdi-arrow-left mr-1"></i> Back</a>
                <div class="">
                    <div class="">
                        <form class="form-horizontal" method="POST" enctype="multipart/form-data" >
                            {% csrf_token %}
                            <div class="form-group row">
                                {% for field in form %}
                                    <div class="col-md-6 mb-2">
                                        {{ field|as_crispy_field }}
                                    </div>
                                {% endfor %}
                                <div class="col-md-12">
                                    {{image_form|crispy}}
                                </div>
                                {% if images%}
                                <div class="row">
                                    {% for img in images %}
                                    <div class="col-lg-3 col-md-6 ">
                                        <div class="card d-block">
                                            <img class="card-img-top img-fluid" src="{{img.imageURL}}" alt="{{img.car}}" class="img-fluid" style="max-height: 250px;">
                                            <div class="card-body p-1">
                                                <a href="{% url 'dashboard:delete-hotel-room-image' id=img.id %}" class="btn btn-sm btn-danger waves-effect waves-light text-white"><i class="mdi mdi-delete mr-1 text-muted"></i>delete</a>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                {% endif %}
                            </div>
                            <div class="clearfix text-right mt-3">
                                <button type="submit" class="btn btn-primary waves-effect waves-light"><i class="fa fa-spinner fa-spin fa-custom-ajax-indicator d-none"></i><i class="mdi mdi-send mr-1"></i> {% if images%}Edit{% else %} Submit{% endif %}</button>
                            </div>
                        </form>
                        </div>
                    
                </div>                   
            </div> 
        </div>
    </div>
</div>




            

{%endblock%}

{% block extra_body %}

    {% endblock %}

dashboard/templates/dashboard/add-property.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-lg-12"> 
        <div class="card">
            <div class="card-body">
                <h4 class="page-title">Create an Asset</h4><br>
                <a href="{% url 'dashboard:property' %}" class="btn btn-primary mb-3"> <i class="mdi mdi-arrow-left mr-1"></i> Back</a>
                <ul class="nav nav-pills navtab-bg nav-justified mb-3">
                    <li class="nav-item">
                        <a href="#lands" data-toggle="tab" aria-expanded="false" class="nav-link active">
                            Lands 
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#appartment" data-toggle="tab" aria-expanded="false" class="nav-link">
                            Buildings/Appartment/House 
                        </a>
                    </li>
                </ul>
                <div class="tab-content">
                    {% include 'dashboard/forms/addproperty.html' %}
                </div>                   
            </div> 
        </div>
    </div>
</div>
{%endblock%}

{% block extra_body %}
<script>
    $('document').ready(function(){
        "use strict";

        // $("#id_purpose").prepend("<option value='' selected='selected'>----</option>");
        // $('#lands #id_purpose').attr('disabled', 'true')
        // $('#lands #id_category').attr('disabled', 'true')
        // $('#lands .col-md-6:eq(1)').hide()
        $('#appartment #id_purpose').change(function(){
            $('.colors').hide();
            $('#' + $(this).val()).show();
            if(($(this).val()) === 'rent'){
                $('#appartment #id_price').attr('placeholder', 'Amount to pay per month')
            }else{
                $('#appartment #id_price').attr('placeholder', 'price')
            }
        }); 
  
    

        function FormAddProperty(FormId, endpoint) {
            $(FormId).submit(function(event) {
                event.preventDefault();
                var formData = new FormData(this);
                $.ajax({
                    url: endpoint,
                    method: "POST",
                    data: formData,
                    beforeSend: function() {
                        $(".fa-custom-ajax-indicator").show();
                    },
                    complete: function() {
                        $(".fa-custom-ajax-indicator").hide();
                    },
                    success: function (response) {
                        $('.error').remove();
                        console.log(response)
                        if(response.error){
                            $.each(response.errors, function(name, error){
                                error = '<small class="text-muted error">' + error + '</small>'
                                $(this).find('[name=' + name + ']').after(error);
                            })
                        }
                        else{
                            
                                window.location.href = "{% url 'dashboard:property' %}";
                            
                        }
                    },
                    cache: false,
                    contentType: false,
                    processData: false,
                    error : function(response){
                        $('.error').remove();
                        console.log(response)
                        
                        
                        if(response.responseJSON.error){
                            console.log("error", response.responseJSON.errors)
                            $.each(response.responseJSON.errors, function(name, error){
                                error = '<small class="text-muted error">' + error + '</small>'
                                $(this).find('[name=' + name + ']').after(error);
                            })
                        }
                    }
                })
            });
        }
        // add Property Land
        FormAddProperty("#form_propertyLand", "{% url 'dashboard:add-land-property' %}")
        FormAddProperty("#form_propertyHouse", "{% url 'dashboard:add-house-property' %}")
    
    });
</script>
    {% endblock %}

dashboard/templates/dashboard/brands.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <a href="{% url 'dashboard:add-brand' %}" class="btn btn-primary mb-3"> <i class="mdi mdi-plus mr-1"></i> New Brand</a>
                <table id="key-datatable" class="table dt-responsive nowrap">
                    <thead>
                        <tr>
                            <td>ID</td>
                            <th>name</th>
                            <th>featured</th>
                            <th>Entry Date</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for brand in brands %}
                        <tr>
                            <td>{{ brand.id }}</td>
                            <td>{{ brand.name }}</td>
                            <td>
                                {% if brand.featured == 1 %}
                                <a href="{% url 'dashboard:featured-brand' id=brand.id%}" class="btn btn-sm btn-danger">remove</a>
                                {% else %}
                                <a href="{% url 'dashboard:featured-brand' id=brand.id%}" class="btn btn-sm btn-primary">add</a>
                                {% endif %}
                            </td>
                            <td>{{ brand.created_at|date:"d- m-Y" }}</td>
                            <td>
                                <div class="btn-group dropdown">
                                    <a href="javascript: void(0);" class="dropdown-toggle arrow-none btn btn-light btn-sm" data-toggle="dropdown" aria-expanded="false"><i class="mdi mdi-dots-horizontal"></i></a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="{% url 'dashboard:view-brand' id=brand.id%}"><i class="mdi mdi-eye mr-1 text-muted"></i>View</a>
                                        <a class="dropdown-item" href="{% url 'dashboard:edit-brand' id=brand.id%}"><i class="mdi mdi-pencil mr-1 text-muted"></i>Edit</a>
                                        <a class="dropdown-item" href="{% url 'dashboard:delete-brand' id=brand.id%}"><i class="mdi mdi-delete mr-1 text-muted"></i>Delete</a>
                                        </div>
                                    </div>
                            </td>
                            
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div> 
        </div> 
    </div>
</div>
{% endblock %}
        

                

dashboard/templates/dashboard/hotels.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <a href="{% url 'dashboard:add-hotel' %}" class="btn btn-primary mb-3"> <i class="mdi mdi-plus mr-1"></i> New Hotel</a>
                <table id="key-datatable" class="table dt-responsive nowrap">
                    <thead>
                        <tr>
                            <td>ID</td>
                            <th>Title</th>
                            <th>Region</th>
                            <th>Locality</th>
                            <th>No. of rooms</th>
                            <th>Featured</th>
                            <th>Entry date</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for hotel in hotels %}
                        <tr>
                            <td>{{ hotel.id }}</td>
                            <td>{{ hotel.title }}</td>
                            <td>{{ hotel.region }}</td>
                            <td>{{ hotel.locality.name }}</td>
                            <td>
                                <div class="button-list">
                                    <button type="button" class="btn btn-primary btn-sm">{{ hotel.num_rooms }}</button>
                                </div>
                            </td>

                            <td>
                                {% if hotel.featured == 1 %}
                                    <a href="{% url 'dashboard:featured-hotel' id=hotel.id%}" class="btn btn-sm btn-danger">Remove</a>
                                {% else %}
                                    <a href="{% url 'dashboard:featured-hotel' id=hotel.id%}" class="btn btn-sm btn-primary">Add</a>
                                {% endif %}
                            </td>
                            <td>{{ hotel.created_at|date:"d- m-Y" }}</td>
                            <td>
                                <div class="btn-group dropdown">
                                    <a href="javascript: void(0);" class="dropdown-toggle arrow-none btn btn-light btn-sm" data-toggle="dropdown" aria-expanded="false"><i class="mdi mdi-dots-horizontal"></i></a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="{% url 'dashboard:view-hotel' id=hotel.id %}"><i class="mdi mdi-eye mr-1 text-muted"></i>View</a>
                                        <a class="dropdown-item" href="{% url 'dashboard:edit-hotel' id=hotel.id %}"><i class="mdi mdi-pencil mr-1 text-muted"></i>Edit</a>
                                        <a class="dropdown-item" href="{% url 'dashboard:delete-hotel' id=hotel.id%}"><i class="mdi mdi-delete mr-1 text-muted"></i>Delete</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div> 
        </div> 
    </div>
</div>
{% endblock %}
        

                

dashboard/templates/dashboard/property.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <a href="{% url 'dashboard:add-property' %}" class="btn btn-primary mb-3"> <i class="mdi mdi-plus mr-1"></i> New Property</a>
                <table id="key-datatable" class="table dt-responsive nowrap">
                    <thead>
                        <tr>
                            <td>ID</td>
                            <th>Title</th>
                            <th>Category</th>
                            <th>Price</th>
                            <th>Purpose</th>
                            <th>Entry date</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for prop in property_list %}
                        <tr>
                            <td>{{ prop.id }}</td>
                            <td>{{ prop.title }}</td>
                            <td>{{ prop.category.title }}</td>
                            <td>&cent; {{ prop.price }}</td>
                            <td>{{ prop.purpose }}</td>
                            <td>{{ prop.created_at|date:"d- m-Y" }}</td>
                            <td>
                                <div class="btn-group dropdown">
                                    <a href="javascript: void(0);" class="dropdown-toggle arrow-none btn btn-light btn-sm" data-toggle="dropdown" aria-expanded="false"><i class="mdi mdi-dots-horizontal"></i></a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="{% url 'dashboard:view-property' id=prop.id %}"><i class="mdi mdi-eye mr-1 text-muted"></i>View</a>
                                        <a class="dropdown-item" href="{% url 'dashboard:edit-property' id=prop.id %}"><i class="mdi mdi-pencil mr-1 text-muted"></i>Edit</a>
                                        <a class="dropdown-item" href="{% url 'dashboard:delete-property' id=prop.id %}"><i class="mdi mdi-delete mr-1 text-muted"></i>Delete</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div> 
        </div> 
    </div>
</div>
{% endblock %}
        

                